version: '3.8'
services:
  crud-db:
    image: postgres:latest
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: nest_crudDB
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
volumes:
  postgres-data:
    driver: local  # Sử dụng driver mặc định cho volume